### PR TITLE
More Assets

### PR DESCRIPTION
**Pull request by JukeDragh**

### CODE REVIEW

**Comment by JukeDragh** [comment]
In case you were wondering, next PR I will have a .txt file for magical/alchemical items that will also be used to phase out placeholder.

**Comment by seiyria** [comment]
What do you mean by replace placeholder

**Comment by JukeDragh** [comment]
The placeholder text file that is used in things such as:
$combat:party#0$ was eyeing up $dict:placeholder$ and $combat:party#1$ got jealous and starting fighting them!
or
%player choked on $dict:placeholder$, coughing it up along with %xpxp.

**Comment by seiyria** [comment]
You don't need to get rid of those. The placeholders are still comical in their own rite. I'd say to add more things around it, but removing them isn't explicitly necessary.

**Comment by JukeDragh** [comment]
Ah, okay. Might just make the reagents one for my own things hehe

**Pull request merged**
