### PR TITLE
fix spelling of all content

### PR DESCRIPTION
**Pull request by sidawson**
6 spell fixes. Readme of commands to do the actual check in the future
(plus detailed explanations). Depends on ok_words and ok_fragments in
Maps repo (dumb, but better to have one global list)

### CODE REVIEW

**Comment by seiyria** [comment]
it's ok, those lists have to be somewhere. in the future what we can do is make them run whenever idlelands CI runs and fail the build based on that. or, even smarter, push them into their own repo and clone them where needed.

**Comment by sidawson** [comment]
At present, it's not robust enough for CI. There are issues, eg in
Heroes.json, people have strings like "\u01ddnl\u0254 ou
\u01dd\u028c\u0250\u0265" - where ou gets pulled out as a separate word. We
can put exceptions in there for that, but it gets messy pretty quickly.
Idlelands is not a simple place.

**Comment by seiyria** [comment]
It never is. Down the line it's something I would like to do if possible. Also, when people are able to submit their own content from the web interface, that will help greatly.

**Comment by sidawson** [comment]
Ahh yes true. Hence the criticality of the "these words are known only in
the IdleLands universe" file - ok_words (& it's cousin ok_fragments).

We should be able to run that over the wiki etc as well.

I'll have a think how to get around the "\u0254 ou \u01dd" unicode mess. As
well as the fact that at the moment those scripts don't deal well with
characters with umlauts, accents etc (ie, non-English alphabet).

**Pull request merged**
